### ISSUE TITLE
Problems because the point and comma are reversed in Spanish 

### ISSUE THREAD

**Issue by daab** [kartik-v/yii2-grid#474]
Hi Kartik, in Spanish I have problems because the point and comma are reversed 
![formato](https://cloud.githubusercontent.com/assets/973814/14768528/dbefe3a0-0a0e-11e6-86cd-c7f5912cc745.png)
as shown in the figure, as I solve this problem so that it looks good. The point is that between decimals and the point is thousands separator. This occurs in the groups, but not total. It also shows wrong numbers, example .3 where it should be 0 and the sums of the groups are not true.

**Comment by kartik-v** [comment]
Read [grid grouping docs](http://demos.krajee.com/grid#grid-grouping) to understand the configuration options for the grid.

You need to configure the `contentFormats` for each column and set `decPoint` and `thousandSep` to the values you need in the `groupHeader` or `groupFooter` setting. This is because formatting for group header and footer is done via javascript and not via Yii formatting engine.

**Comment by daab** [comment]
Hi Kartik, The problem is with function formatNumber, in line 57, in array result ['0','3'], when to be ['0','0'].

**Comment by brianse** [comment]
I also got the problem same daab. I found that when I put numbers such as 6.00, 6.00, 5.00. The summary is 17.3 where it should be 17.00. After deeply debugging, I guess the problem could be happen in kv-grid-group.js file at line 49. 
```
formatNumber = function (number, decimals, dec_point, thousands_sep) {
    number = (number + '').replace(/[^0-9+\-Ee.]/g, '');
    var n = !isFinite(+number) ? 0 : +number, s,
        prec = !isFinite(+decimals) ? 0 : Math.abs(decimals),
        sep = (typeof thousands_sep === 'undefined') ? ',' : thousands_sep,
        dec = (typeof dec_point === 'undefined') ? '.' : dec_point,
        toFixedFix = function (n, prec) {
            var k = Math.pow(10, prec);
            return '' + Math.round(n * k) / k; // <--- This line got problem
        };
    s = (prec ? toFixedFix(n, prec) : '' + Math.round(n)).split('.');
    if (s[0].length > 3) {
        s[0] = s[0].replace(/\B(?=(?:\d{3})+(?!\d))/g, sep);
    }
    if ((s[1] || '').length < prec) {
        s[1] = s[1] || '';
        s[1] += [(prec - s[1].length + 1)].join('0');
    }
    return s.join(dec);
};
```
As you can see, the toFixedFix function return an integer number (Ex: 17), thefore, Math.round(n)).split('.') will got null, and the statement  s[1] += [(prec - s[1].length + 1)].join('0') will set s[1] to 3 (2 - 0 + 1). For temporary solving problem, I try to fix the line got problem as
 
`return '' + (Math.round(n * k) / k).toFixed(prec);`

Now, the result is correct (17.00). Could you please check it, Kartik ?

**Comment by kartik-v** [comment]
I do not think you folks are using the latest release of the extension. You seem to have an old outdated code. Update to latest from.dev master and check.

**Comment by brianse** [comment]
Thank you, Kartik. However, after I updated your extension from 3.1.1 to 3.1.2 (newest), the kv-grid-group.js file throw an exception in line 52
`num = n.toFixed(Math.max(0, Math.floor(d)));`
The error message is 
> n.toFixed is not a function

This is my parameter pass to function 
> n = 20.55
> d = 2
> c = .
> s = ,
> x = undefined

Did I do something wrong?

**Comment by kartik-v** [comment]
Not sure why is that ... 

The [toFixed method](http://www.w3schools.com/jsref/jsref_tofixed.asp) is a standard javascript function.

**Comment by kartik-v** [comment]
Not sure why is that ... 

The [toFixed method](http://www.w3schools.com/jsref/jsref_tofixed.asp) is a standard javascript function.

You may want to check if the error is happening at a place where the value of  `n` is invalid and not numeric or something...

**Comment by kartik-v** [comment]
I provided an enhancement to address wrong data types - you may check again with latest updated extension code.

**Comment by brianse** [comment]
Everything works fine, now. Thank you very much for your quick kindly support!
